name: Lint and format checks

on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
  
    - run: npm ci

    - name: Lint
      run: npm run lintCheck

    - name: Prettier
      run: npm run formatCheck
